### PR TITLE
fix(ui): adding little margin

### LINKED ISSUE #522: Sumber text are too close with the content
## Description

Open https://www.wargabantuwarga.com/faq, scroll down until you found the content with the "sumber" text.

Preview:

Screenshot_20210731-173049_Chrome

## Expected Behaviour

Adding a gap between the content and the "sumber" text, maybe adding class `mt-2`

### PR DESCRIPTION
**Pull request by burhanahmeed**
Closes #522 
## Description

Adding `mt-2` to `<small>` tag. Seems a very little difference though.

**Before**
image

**After**
image

### CODE REVIEW

File: pages/faq.tsx [hunk 1]
```diff
@@ -115,7 +115,7 @@ export default function FaqPage(props: FaqPageProps) {
                       <p className="text-base text-gray-500">
                         {htmr(question.jawaban)}
                       </p>
-                      <small>
+                      <small className="mt-2 inline-block">
```
Comment (zainfathoni) [inline pages/faq.tsx:118]:
```suggestion
                      <small className="mt-4 inline-block">
```
If `mt-2` is too little, let's try `mt-4`, then.

**Review by zainfathoni — CHANGES_REQUESTED** [review]

File: pages/faq.tsx (hunk 1 above)
Comment (burhanahmeed) [reply pages/faq.tsx]: updated to `mt-4`
image

**Review by resir014 — DISMISSED** [review]
I think it's better that we add `space-y-N` utility on the wrapping `<dd>` element instead of just adding a `mt-N`, just in case we're adding some more elements in this little `<dd>`

The `space-y-N` utility evenly spaces all child elements vertically by the set margin. ([docs](https://tailwindcss.com/docs/space))

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks for working on it @burhanahmeed! 🙏

**Comment by zainfathoni** [comment]
@all-contributors please add @burhanahmeed for code
