### PR TITLE
fix: refactor mobile search form

### LINKED ISSUE #444: Refactor Mobile Search Form
## Description
Just like suggested in #421, to reduce search form space, change mobile search form styling just like desktop version 

Current:

Expected:
Screen Shot 2021-07-25 at 22 02 00

## Tasks

- [x] Move cari button inline with keyword input
- [x] Show 2 filter items per row (2 column grid)

### PR DESCRIPTION
**Pull request by ekamuktia**
Closes #444

## Description
To reduce search form space, change mobile search form styling just like desktop version

Problem found: on original styling, the primary button default size is `md` which has class `text-sm`. This styling causing the keyword input and `cari` button have different height in mobile. 

image

## Current Tasks
- [x] Move `cari` button inline with keyword input
- [x] Change default size of Primary Button as `undefined` to enable `text-base sm:text-sm` styling so it won't affect other buttons and make keyword input & `cari` button have same height in mobile
- [x] Show 2 filter items per row (2 column grid)
- [x] Update test case

### CODE REVIEW

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, Mbak @ekamuktia! 🙏

File: components/ui/button/primary-button.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ export const PrimaryButton = React.forwardRef<HTMLButtonElement, ButtonProps>(
       style,
       type,
       block,
-      size = "md",
+      size,
```
Comment (resir014) [inline components/ui/button/primary-button.tsx:29]: Why is this change necessary?

File: components/ui/button/utils/helpers.ts [hunk 2]
```diff
@@ -32,7 +32,7 @@ export function buttonSizes(size?: ButtonSizes) {
       return "px-6 py-3 text-base";
     }
     default: {
-      return "px-4 py-2 text-sm";
+      return "px-4 py-2 text-base sm:text-sm";
```
Comment (resir014) [inline components/ui/button/utils/helpers.ts:35]: This shouldn't be changed as this will cause the button to have different height for the button.

image

**Review by resir014 — CHANGES_REQUESTED** [review]

**Comment by resir014** [comment]
Please check again @ekamuktia. In general, the button sizes **shouldn't** be changed.

**Comment by resir014** [comment]
@ekamuktia Decided to fix the form styles myself so all you need to do is revert the button styling.

#474

File: components/ui/button/utils/helpers.ts (hunk 2 above)
Comment (ekamuktia) [reply components/ui/button/utils/helpers.ts]: Reverted

**Review by resir014 — APPROVED** [review]
